apiVersion: apps/v1
kind: Deployment
metadata:
  name: gre5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gre5
  template:
    metadata:
      labels:
        app: gre5
    spec:
      containers:
      - image: okteto.dev/gre5:latest
        name: gre5
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ad8b293e-dcfb-4497-bcab-4f98424d5236"
        - name: Vless_Path
          value: "/vlhui555"
        - name: Vmess_UUID
          value: "ad8b293e-dcfb-4497-bcab-4f98424d5236"
        - name: Vmess_Path
          value: "/vmyg666"
        - name: Share_Path
          value: "/v2link"
