apiVersion: v1
kind: Service
metadata:
  name: gre5
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "gre5"
    port: 8080
  selector:
    app: gre5
